version: '{branch}-{build}'
os: Visual Studio 2015
clone_folder: C:\projects\openvdb

configuration:
    - Release
platform:
    - x64
environment:
  CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"

install:
  # ZLIB
  - appveyor DownloadFile https://github.com/madler/zlib/archive/v1.2.8.tar.gz
  - 7z x v1.2.8.tar.gz -so | 7z x -si -ttar
  - cd zlib-1.2.8
  - cmake -G "%CMAKE_PLATFORM%" . -DCMAKE_INSTALL_PREFIX=C:/Sys
  #- cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ..

  # OpenEXR
  #- set EXRINSTALLDIR=%APPVEYOR_BUILD_FOLDER%/deps/openexr-install
  #- set EXRVERSION=2.2.0
  #- mkdir openexr-install
  - git clone -b v2.2.0 https://github.com/openexr/openexr.git ./openexr
  - cd openexr
  - dir
  - cd IlmBase
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" --config Release ..
  #- cmake --build . --config Release
  - cmake --build . --config Release --target install
  - dir C:\Sys
  - dir C:\Sys\lib
  - dir C:\Sys\include
  - cd ../../OpenEXR
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" --config Release -DILMBASE_PACKAGE_PREFIX="C:/Program Files/ILMBase" ..
  #- cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../../..
  - dir

  # Boost
  - set BOOST_ROOT=C:\Libraries\boost_1_59_0
  - dir %BOOST_ROOT%
  - set BOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%

build_script:
  - echo Running cmake...
  - cd c:\projects\openvdb
  - mkdir build
  - mkdir build\windows64
  - cd build\windows64
  - cmake -G "%CMAKE_PLATFORM%" --config Release ../..
  - dir c:\projects\openvdb
  - dir c:\projects\openvdb\build
  - dir c:\projects\openvdb\build\windows64
  - cmake --build . --config %CONFIGURATION%

matrix:
    fast_finish: true
