version: '{branch}-{build}'
os: Visual Studio 2015
clone_folder: C:\projects\openvdb

configuration:
    - Release
platform:
    - x64
environment:
  CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"

install:
  - cd C:\Libraries\boost_1_59_0
  - dir
  - rename lib64-msvc-14.0 lib
  - dir
  - cd c:/projects/openvdb

  # vfxcmake  
  - mkdir deps
  - cd deps
  - git clone https://github.com/caron/vfxcmake.git ./vfxcmake

  # GLFW
  - appveyor DownloadFile https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.bin.WIN64.zip
  - 7z x glfw-3.2.bin.WIN64.zip
  - cd c:/projects/openvdb/deps

  # GLEW
  - appveyor DownloadFile http://downloads.sourceforge.net/project/glew/glew/1.10.0/glew-1.10.0-win32.zip
  - 7z x glew-1.10.0-win32.zip
  - cd c:/projects/openvdb/deps

  # ZLIB
  - appveyor DownloadFile https://github.com/madler/zlib/archive/v1.2.8.tar.gz
  - 7z x v1.2.8.tar.gz -so | 7z x -si -ttar
  - cd zlib-1.2.8
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_INSTALL_PREFIX=C:/zlib ..
  - cmake --build . --config Release --target install
  - cd c:/projects/openvdb/deps

  # Blosc
  - git clone -b v1.5.2 https://github.com/Blosc/c-blosc.git ./blosc
  - cd blosc
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" --config Release -DCMAKE_INSTALL_PREFIX=C:/blosc -DZLIB_ROOT=C:/zlib ..
  - cmake --build . --config Release --target install
  - cd c:/projects/openvdb/deps

  # OpenEXR and ILMBase
  - git clone -b v2.2.0 https://github.com/openexr/openexr.git ./openexr
  - cd openexr
  - cd IlmBase
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" --config Release -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX="C:/ilmbase" -DNAMESPACE_VERSIONING=0 ..
  - cmake --build . --config Release --target install
  - cd ../../OpenEXR
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_PLATFORM%" --config Release -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX="C:/openexr" -DILMBASE_PACKAGE_PREFIX="C:/ilmBase" -DNAMESPACE_VERSIONING=0 -DUSE_ZLIB_WINAPI=0 -DZLIB_ROOT=C:/zlib ..
  - cmake --build . --config Release --target install
  - cd c:/projects/openvdb/deps

  # TBB
  - appveyor DownloadFile https://www.threadingbuildingblocks.org/sites/default/files/software_releases/windows/tbb44_20160526oss_win_0.zip
  - 7z x tbb44_20160526oss_win_0.zip
  - dir
  - cd tbb44_20160526oss
  - dir
  - cd c:/projects/openvdb/deps
  - dir

  # Boost
  - set BOOST_ROOT=C:\Libraries\boost_1_59_0
  - set BOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%

build_script:
  - echo Running cmake...
  - cd c:\projects\openvdb
  - mkdir build
  - mkdir build\windows64
  - cd build\windows64
  - cmake -G "%CMAKE_PLATFORM%" --config Release -DCMAKE_MODULE_PATH=c:/projects/deps/vfxcmake/cmake ../..
  - dir c:\projects\openvdb
  - dir c:\projects\openvdb\build
  - dir c:\projects\openvdb\build\windows64
  - cmake --build . --config %CONFIGURATION%

matrix:
    fast_finish: true
